### ISSUE TITLE
How to brand component demos?

### ISSUE THREAD

**Issue by notlee** [Financial-Times/o-brand#31]
Our component demos may include scss which requires branding. Demo scss may use brand variables and may use branded colour usecases `@include oColorsFor(page);`, but may sometimes need a demo specific brand variable. What should our approach to that be?

- Add demo variables when calling `oBrandDefine`? Demo variables in prod code is unpleasant. 😷 
- Rely on conditionals `background: if ($o-brand == 'whitelabel', oColorsGetPaletteColor('black'), oColorsGetPaletteColor('slate'));` Does not adapt well to adding or modifying brands 😷
- Or...

**Comment by chee** [comment]
i think i'd do:

```
@if ($o-brand == 'whitelabel') {
  .demo-thing {
    /* code here */
  }
}

@if ($o-brand == 'master') {
  .demo-thing {
    /* code here */
  }
}
```

how long do we keep discussion issues open?

**Comment by JakeChampion** [comment]
I'd say let's close the issue - we are currently researching design-tokens and how they might change our branding and theming approaches within components

In the interim, the code example chee gave looks good 👍
